issues:
  max-per-linter: 0
  max-same-issues: 0

run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - vet
    - vetshadow

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
