---
name: Issue Triage

on:
  issues:
    types:
    - opened

jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Issue Triage Labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler-issues.yml
          enable-versioned-regex: 0
          include-title: 1
