name: "Stale issues and pull requests"

on:
  schedule:
  - cron: "30 17 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 100
          days-before-stale: 60
          days-before-close: 30
          exempt-issue-labels: 'needs-triage'
          exempt-pr-labels: 'needs-triage'
          stale-issue-label: 'stale'
          stale-issue-message: |
            Marking this issue as stale due to inactivity. This helps us focus on the active issues. If this issue receives no comments in the next 30 days it will automatically be closed.
            If this issue was automatically closed and you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thank you!
          stale-pr-label: 'stale'
          stale-pr-message: |
            Marking this pull request as stale due to inactivity. This helps us focus on the active pull requests. If this pull request receives no comments in the next 30 days it will automatically be closed.
            If this pull request was automatically closed and you feel this pull request should be reopened, we encourage creating a new pull request linking back to this one for added context. Thank you!
