---
name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  gotest:
    name: gotest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: 'go.mod'
      - name: Go Build
        run: go build -v ./.
      - name: Go Test
        run: go test ./... -timeout=30s -parallel=4
